import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeroSection from '@/app/custom-components/Navbar'
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Raman's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
  <HeroSection/>
    {children}

  </>
  );
}
